### ISSUE TITLE
gradle: Listing tasks fails

### ISSUE THREAD

**Issue by jvff** [lnls-dig/halcs#142]
Running `./gradlew tasks` leads to the following error:

    :tasks FAILED
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Build file '/project/examples/build.gradle' line: 2
    
    * What went wrong:
    A problem occurred evaluating project ':examples'.
    > Cannot add rule components { ... } @ examples/build.gradle line 2, column 5 for model element 'components' at state DefaultsApplied as this element is already at state GraphClosed.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

The stacktrace of the problem is:

    * Exception is:
    org.gradle.api.GradleScriptException: A problem occurred evaluating project ':examples'.
            at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
            at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:177)
            at org.gradle.api.internal.project.DeferredProjectConfiguration.fire(DeferredProjectConfiguration.java:61)
            at org.gradle.api.internal.project.DefaultProject.fireDeferredConfiguration(DefaultProject.java:1080)
            at org.gradle.api.internal.tasks.DefaultTaskContainer.discoverTasks(DefaultTaskContainer.java:198)
            at org.gradle.api.internal.resolve.DefaultProjectModelResolver.resolveProjectModel(DefaultProjectModelResolver.java:40)
            at org.gradle.nativeplatform.internal.resolve.CurrentProjectModelResolver.resolveProjectModel(CurrentProjectModelResolver.java:37)
            at org.gradle.api.internal.resolve.ProjectModelResolver$resolveProjectModel.call(Unknown Source)
            at br.lnls.dig.gradle.nativedistribution.plugins.RpmInstallationPlugin.getDistributions(RpmInstallationPlugin.groovy:142)
            at br.lnls.dig.gradle.nativedistribution.plugins.RpmInstallationPlugin.getDistributionsAfter(RpmInstallationPlugin.groovy:128)
            at br.lnls.dig.gradle.nativedistribution.plugins.RpmInstallationPlugin.distributionsFromProjectsAfter(RpmInstallationPlugin.groovy:108)
            at org.gradle.model.internal.method.WeaklyTypeReferencingMethod.invoke(WeaklyTypeReferencingMethod.java:100)
            at org.gradle.model.internal.inspect.DefaultModelRuleInvoker.invoke(DefaultModelRuleInvoker.java:36)
            at org.gradle.model.internal.inspect.MethodBackedModelAction.execute(MethodBackedModelAction.java:45)
            at org.gradle.model.internal.inspect.AbstractMethodRuleAction.execute(AbstractMethodRuleAction.java:48)
            at org.gradle.model.internal.inspect.ModelRuleExtractor$DefaultExtractedRuleSource$ContextualizedModelAction.execute(ModelRuleExtractor.java:515)
            at org.gradle.model.internal.registry.DefaultModelRegistry$4.run(DefaultModelRegistry.java:455)
            at org.gradle.model.internal.registry.RuleContext.run(RuleContext.java:42)
            at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(DefaultModelRegistry.java:452)
            at org.gradle.model.internal.registry.DefaultModelRegistry.access$700(DefaultModelRegistry.java:41)
            at org.gradle.model.internal.registry.DefaultModelRegistry$RunModelAction.apply(DefaultModelRegistry.java:1154)
            at org.gradle.model.internal.registry.DefaultModelRegistry.transitionTo(DefaultModelRegistry.java:360)
            at org.gradle.model.internal.registry.DefaultModelRegistry.get(DefaultModelRegistry.java:330)
            at org.gradle.model.internal.registry.DefaultModelRegistry.require(DefaultModelRegistry.java:310)
            at org.gradle.model.internal.registry.DefaultModelRegistry.realizeNode(DefaultModelRegistry.java:232)
            at org.gradle.api.internal.tasks.DefaultTaskContainer.realize(DefaultTaskContainer.java:187)
            at org.gradle.api.internal.project.DefaultProjectTaskLister.listProjectTasks(DefaultProjectTaskLister.java:29)
            at org.gradle.api.tasks.diagnostics.TaskReportTask.generate(TaskReportTask.java:76)
            at org.gradle.api.tasks.diagnostics.AbstractReportTask$2.generateReport(AbstractReportTask.java:73)
            at org.gradle.api.tasks.diagnostics.internal.ReportGenerator.generateReport(ReportGenerator.java:58)
            at org.gradle.api.tasks.diagnostics.AbstractReportTask.generate(AbstractReportTask.java:79)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
            at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:133)
            at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:126)
            at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:115)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
            at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
            at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
            at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
            at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
            at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
            at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
            at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
            at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
            at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
            at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
            at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
            at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
            at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
            at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
            at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
            at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
            at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
            at org.gradle.internal.Factories$1.create(Factories.java:22)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
            at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
            at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
            at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
            at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
            at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
            at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
            at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
            at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
            at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
            at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:82)
            at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
            at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
            at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
            at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
            at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:49)
            at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
            at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
            at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
            at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
            at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
            at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
            at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
            at org.gradle.util.Swapper.swap(Swapper.java:38)
            at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
            at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
            at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
            at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
            at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
            at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
            at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
            at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
            at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
            at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
            at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
            at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
            at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
            at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:240)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
            at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    Caused by: java.lang.IllegalStateException: Cannot add rule components { ... } @ examples/build.gradle line 2, column 5 for model element 'components' at state DefaultsApplied as this element is already at state GraphClosed.
            at org.gradle.model.internal.registry.RuleBinder$1.execute(RuleBinder.java:50)
            at org.gradle.model.internal.registry.RuleBinder$1.execute(RuleBinder.java:44)
            at org.gradle.model.internal.registry.PathBinderCreationListener.doOnBind(PathBinderCreationListener.java:43)
            at org.gradle.model.internal.registry.ModelBinding.onBind(ModelBinding.java:79)
            at org.gradle.model.internal.registry.RuleBindings.bound(RuleBindings.java:51)
            at org.gradle.model.internal.registry.RuleBindings.access$400(RuleBindings.java:27)
            at org.gradle.model.internal.registry.RuleBindings$PredicateMatches.add(RuleBindings.java:142)
            at org.gradle.model.internal.registry.RuleBindings$PathPredicateIndex.addReference(RuleBindings.java:160)
            at org.gradle.model.internal.registry.RuleBindings.addRule(RuleBindings.java:79)
            at org.gradle.model.internal.registry.RuleBindings.add(RuleBindings.java:65)
            at org.gradle.model.internal.registry.DefaultModelRegistry.bindInternal(DefaultModelRegistry.java:165)
            at org.gradle.model.internal.registry.DefaultModelRegistry.configure(DefaultModelRegistry.java:100)
            at org.gradle.model.internal.registry.DefaultModelRegistry.configure(DefaultModelRegistry.java:40)
            at org.gradle.model.dsl.internal.TransformedModelDslBacking.registerAction(TransformedModelDslBacking.java:73)
            at org.gradle.model.dsl.internal.TransformedModelDslBacking.configure(TransformedModelDslBacking.java:50)
            at org.gradle.model.dsl.internal.TransformedModelDslBacking$configure.call(Unknown Source)
            at build_8b1618ula7n9gebg5kojxnz00$_run_closure1.doCall(/project/examples/build.gradle:2)
            at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
            at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:52)
            at org.gradle.api.internal.project.DefaultProject.model(DefaultProject.java:1062)
            at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
            at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
            at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
            at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
            at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
            at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
            at build_8b1618ula7n9gebg5kojxnz00.run(/project/examples/build.gradle:1)
            at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
            ... 106 more

**Comment by lerwys** [comment]
not using gradle anymore
